[[permission]]
identifier = "app-commands"
description = "Launcher application commands"
commands.allow = [
  "get_app_version",
  "get_vh_version",
  "check_and_sync_media",
  "get_vh_release_notes",
  "check_launcher_update",
  "perform_launcher_update",
  "check_patch_status",
  "switch_method",
  "start_installation",
  "check_game_folder_write_access",
  "launch_game",
  "force_quit_game",
  "uninstall",
  "restart_as_admin",
  "upload_logs",
  "notify_ui_interactive",
  "reset_webview_cache"
]
